var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                            xxxxx           xx  ",
   "  xx                                                        x!!!x            x  ",
   "  x                                                         x!!!x            x  ",
   "  x                                               s         xvvvx            x  ",
   "  x                                                                          x  ",
   "  x                                    s                                     x  ",
   "  x                            s                                             x  ",
   "  x           s        s                   o      s                          x  ",
   "  x                                o                                       o x  ",
   "  x                        o             xxxxx                               x  ",
   "  x  @             o             xxxxx   x   x                               x  ",
   "  xxxxxxxxx              xxxxx   x   x   x   x       xxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "          x      xxxxx   x   x   x   x   x   x       x                          ",
   "          x!!!!!!x   x!!!x   x!!!x   x!!!x   x!!!!!!!x                          ",
   "          x!!!!!!x   x!!!x   x!!!x   x!!!x   x!!!!!!!x                          ",
   "          xxxxxxxx   xxxxx   xxxxx   xxxxx   xxxxxxxxx                          ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                                      ",
   "  xx      xxx          x                                         x                                    ",
   "  x       x!x          x                                         x                                    ",
   "  x       xvx          x                                         x                                    ",
   "  x                    x                                         x                                    ",
   "  x                    x                                         x                                    ",
   "  x                    x              xxxxxxxxxx                 x                                    ",
   "  x                    x              x=       x                 x                                    ",
   "  x  @                 x              x    o   x                 x                                    ",
   "  xxxxxxxxx xxxxxxxx   x              x       =x                 x                                    ",
   "  x                    x              xxx    xxx             xxx x                                    ",
   "  x                  o x                                     x!x x                                    ",
   "  x                    x                            o        xvx x                                    ",
   "  x                    x             s           s      s        x                                    ",
   "  x   xxxxx xxxxxxxxxxxx                 xxxx                    x                                    ",
   "  x                        s             x  x                    x                               xx   ",
   "  x o                                    x  x                    x                                x   ",
   "  x                             o       xx  xxxxx       xxxx     x                                x   ",
   "  x                                      x  x              x     x                                x   ",
   "  xxxxxxxxx xxxxxxxxxxxx      xxxxx      x  x!!!!!!!!!!!!!!x     x                                x   ",
   "  x!!!!!!!!!!!!!!!!!!!!x!!!!!!x   x!!!!!!x  x!!!!!!!!!!!!!!x     x                                x   ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    ox                        o    s  x   ",
   "                                                           x    xx                                x   ",
   "                                                           xo    x                    o  xxx      x   ",
   "                                                           xx    x                                x   ",
   "                                                           x     x               o   xxx          x   ",
   "                                                           x    ox                              o x   ",
   "                                                           x    xx          o   xxx               x   ",
   "                                                           x     x                                x   ",
   "                                                           x               xxx                    x   ",
   "                                                           x                                      x   ",
   "                                                           x         =                =           x   ",
   "                                                           xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   "],
  ["                                                                                                           ",
   "                                                                                                           ",
   " xx                                                                     xx                                 ",
   " x                                                                       x                                 ",
   " x                 |    o                                                x                                 ",
   " x                                                                       x                                 ",
   " x  @       xxxxx     xxxxx   |                                        o x                                 ",
   " xxxxxxxxxxxx                      o                                     x                                 ",
   " x                                                                    xxxx                                 ",
   " x                               xxxxx                               xx                                    ",
   " x                      o                                             x                                    ",
   " x                                                                    x                                    ",
   " x                |   xxxxx                                           x                                    ",
   " x                                                                   xx                                    ",
   " x    s      o                                                        x                                    ",
   " x                                                                    x                                    ",
   " x         xxxxx                                                      x                                    ",
   " x                                                                   xx                                    ",
   " x                                                                    x                                    ",
   " x                                           s                        x                                    ",
   " x    s      o   s    o                                               x                                    ",
   " x                                    o            o                 xx                                    ",
   " x                                                                    x                                    ",
   " x                                  xxxxx        xxxxx                x                                    ",
   " x                                                         x     =    x                                    ",
   " xxxxxxxxxx    xxxxx    xxxxxxxx                           xxxxxxxxxxxx                                    ",
   "          x!!!!x   x!!!!x      x!!!!!!!!!!!!!!!!!!!!!!!!!!!x                                               ",
   "          xxxxxx   xxxxxx      xxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                               ",
   "                                                                                                           ",
   "                                                                                                           ",
   "                                                                                                           ",
   "                                                                                                           "],
  ["                                                                                                  ",
   "                                                                                                  ",
   "           xxx                                                                                    ",
   "  x        x!x                                                                                    ",
   "  x        xvx                                                                                    ",
   "  x                                                                                               ",
   "  x             s    o                          xxxxxxxxxxxxxxxxxxxxxxxxxxx                       ",
   "  x                                             x                         x                       ",
   "  x                 xxx  s                      x                         x                       ",
   "  x                                s            x     s                   x                       ",
   "  x                           o                 x                         x                       ",
   "  x      x      x                               x     o                   x                       ",
   "  x      x  o   x            xxx                x    xxx                  x                       ",
   "  x      x      x                               x |  x x                  x                       ",
   "  x      x      x                  s   o        x    x x                  x                       ",
   "  x      x  o   x                               x  o x xo                 x                       ",
   "  x      x      x                     xxx       x    x xx                 x                       ",
   "  x      xxxxxxxx                               xx   x x                  x                       ",
   "  x                           o                 x    x x                  x                       ",
   "  x                                s            x    x xo                 x                       ",
   "  x                          xxx                x o  x xx    s            x                       ",
   "  x                                    o        x    x x     o            x                       ",
   "  x                                             x    x x                  x                       ",
   "  x                                   xxx       x | xx x                  x                       ",
   "  x                                                  x xxxx    xxx        x                       ",
   "  x                                                  x    x!!!!x x        x                       ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx xxxx     x                       ",
   "  x                                                                       x                       ",
   "  x                  |                |                                  ox                       ",
   "  x                                                                      xx                       ",
   "  x              o       o         o                                      x                       ",
   "  x         |                 |               x        x         x        x                       ",
   "  x  @                                        x    =   x    =    x        x                       ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                       ",
   "                                                                                                  ",
   "                                                                                                  "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
